import shutil
import subprocess
import unittest
import os
import json
import tempfile
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
UTILS_PATH = REPOSITORY_ROOT / "scripts" / "utils.sh"


def bash_executable():
    if os.name == "nt":
        for candidate in (
            Path(os.environ.get("ProgramFiles", "")) / "Git" / "bin" / "bash.exe",
            Path(os.environ.get("ProgramW6432", "")) / "Git" / "bin" / "bash.exe",
        ):
            if candidate.is_file():
                return str(candidate)
    return shutil.which("bash")


def compose_command():
    docker_compose = shutil.which("docker-compose")
    if docker_compose:
        return [docker_compose]

    docker = shutil.which("docker")
    if docker:
        result = subprocess.run(
            [docker, "compose", "version"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return [docker, "compose"]

    raise unittest.SkipTest("Docker Compose CLI is required for Compose contract tests")


class N8nApiKeyContractTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if bash_executable() is None:
            raise unittest.SkipTest("bash is required for shell contract tests")

    def run_validator(self, profiles, key):
        command = (
            f'source "{UTILS_PATH}"; '
            f'require_n8n_mcp_api_key "{profiles}" "{key}"'
        )
        environment = os.environ.copy()
        if os.name == "nt":
            git_usr_bin = Path(os.environ.get("ProgramFiles", "")) / "Git" / "usr" / "bin"
            environment["PATH"] = os.pathsep.join(
                [str(git_usr_bin), environment.get("PATH", "")]
            )
        return subprocess.run(
            [bash_executable(), "-c", command],
            cwd=REPOSITORY_ROOT,
            check=False,
            capture_output=True,
            text=True,
            env=environment,
        )

    def render_compose(self, profiles, api_key=None, mcp_token="synthetic-mcp-token"):
        environment = {
            key: os.environ[key]
            for key in ("PATH", "SystemRoot", "COMSPEC")
            if key in os.environ
        }
        environment.update(
            {
                "COMPOSE_DISABLE_ENV_FILE": "1",
                "COMPOSE_PROFILES": profiles,
                "N8N_MCP_TOKEN": mcp_token,
            }
        )
        if api_key is not None:
            environment["N8N_API_KEY"] = api_key

        with tempfile.TemporaryDirectory() as docker_config:
            environment["DOCKER_CONFIG"] = docker_config
            command = [*compose_command(), "config", "--format", "json"]
            result = subprocess.run(
                command,
                cwd=REPOSITORY_ROOT,
                check=False,
                capture_output=True,
                text=True,
                env=environment,
            )
        self.assertEqual(result.returncode, 0)
        return json.loads(result.stdout)

    def test_generator_does_not_classify_n8n_api_key_as_generated_secret(self):
        source = (REPOSITORY_ROOT / "scripts" / "03_generate_secrets.sh").read_text(encoding="utf-8")

        self.assertNotRegex(
            source,
            r'\["N8N_API_KEY"\]\s*=\s*"apikey:',
            "N8N_API_KEY must be supplied externally, not generated by the wizard",
        )

    def test_generator_keeps_inbound_mcp_token_generation(self):
        source = (REPOSITORY_ROOT / "scripts" / "03_generate_secrets.sh").read_text(encoding="utf-8")
        self.assertRegex(source, r'\["N8N_MCP_TOKEN"\]\s*=\s*"apikey:32"')

    def test_generator_validates_an_existing_n8n_mcp_profile_before_side_effects(self):
        source = (REPOSITORY_ROOT / "scripts" / "03_generate_secrets.sh").read_text(encoding="utf-8")
        validation = source.index("require_n8n_mcp_api_key")
        caddy_install = source.index("# Install Caddy")
        self.assertLess(validation, caddy_install)

    def test_wizard_validates_selected_n8n_mcp_profile(self):
        source = (REPOSITORY_ROOT / "scripts" / "04_wizard.sh").read_text(encoding="utf-8")
        validation = source.index("require_n8n_mcp_api_key")
        profile_write = source.index("# Update or add COMPOSE_PROFILES")
        self.assertLess(validation, profile_write)

    def test_service_runner_validates_before_launching_services(self):
        source = (REPOSITORY_ROOT / "scripts" / "05_run_services.sh").read_text(encoding="utf-8")
        validation = source.index("require_n8n_mcp_api_key")
        launch = source.index("./start_services.py")
        self.assertLess(validation, launch)

    def test_n8n_mcp_rejection_does_not_echo_supplied_secret(self):
        generic_secret = "a" * 32
        result = self.run_validator("n8n-mcp", generic_secret)
        self.assertNotIn(generic_secret, result.stdout + result.stderr)

    def test_n8n_mcp_requires_an_external_public_api_jwt(self):
        result = self.run_validator("n8n,n8n-mcp", "")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("N8N_API_KEY", result.stdout + result.stderr)

    def test_n8n_mcp_rejects_a_generic_hex_secret(self):
        result = self.run_validator("n8n-mcp", "a" * 32)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("public API JWT", result.stdout + result.stderr)

    def test_non_n8n_mcp_profiles_allow_missing_api_key(self):
        result = self.run_validator("n8n,langfuse", "")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_non_n8n_mcp_profiles_ignore_an_invalid_api_key(self):
        result = self.run_validator("n8n,langfuse", "not-a-jwt")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_n8n_mcp_accepts_public_api_audience_jwt_shape(self):
        synthetic_public_api_jwt = (
            "eyJhbGciOiJIUzI1NiJ9."
            "eyJhdWQiOiJwdWJsaWMtYXBpIn0."
            "synthetic-signature"
        )

        result = self.run_validator("n8n-mcp", synthetic_public_api_jwt)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_n8n_mcp_rejects_a_jwt_for_a_different_audience(self):
        wrong_audience_jwt = (
            "eyJhbGciOiJIUzI1NiJ9."
            "eyJhdWQiOiJvdGhlciJ9."
            "synthetic-signature"
        )
        result = self.run_validator("n8n-mcp", wrong_audience_jwt)

        self.assertNotEqual(result.returncode, 0)

    def test_compose_maps_distinct_mcp_and_public_api_credentials(self):
        synthetic_public_api_jwt = (
            "eyJhbGciOiJIUzI1NiJ9."
            "eyJhdWQiOiJwdWJsaWMtYXBpIn0."
            "synthetic-signature"
        )
        config = self.render_compose("n8n-mcp", api_key=synthetic_public_api_jwt)
        service_environment = config["services"]["n8n-mcp"].get("environment", {})
        self.assertEqual(service_environment.get("AUTH_TOKEN"), "synthetic-mcp-token")
        self.assertEqual(service_environment.get("N8N_API_KEY"), synthetic_public_api_jwt)

    def test_compose_without_n8n_mcp_allows_missing_public_api_key(self):
        config = self.render_compose("n8n", api_key=None)
        self.assertNotIn("n8n-mcp", config["services"])


if __name__ == "__main__":
    unittest.main()
